Bump minimun Elixir version to 1.14 (breaking change)
Nx requires minimun Elixir 1.14 and OTP 24

Updating image on a project failed with:

== Compilation error in file lib/image/exif/decode.ex ==
Error: ** (CompileError) lib/image/exif/decode.ex:138: size in bitstring expects an integer or a variable as argument, got: :erlang.*(:erlang.byte_size(value), 8)

Then working on a fix I realized I was not able to compile it due not meeting Nx requirements:

Error while loading project :nx
** (Mix) Nx requires Erlang/OTP 24+
==> nx
warning: the dependency :nx requires Elixir "~> 1.14" but you are running on v1.12.3

Since image optionally depends on Nx, seems like it's a good measure to bump the minimum Elixir version to 1.14
and test the minimuun required OTP/Elixir on CI, which fixes the initial issue I found too, even though this is a breaking change.